### ISSUE TITLE
Understanding some attributes

### ISSUE THREAD

**Issue by frodoe7** [fabiensabatie/yieldfinity#11]
I'm using this library in some side project,
would like to ask in which currency these attributes are?

for example in BNBUSDT market
console.log(strategy.profit) // 11.23
console.log(strategy.capitalInvested) // 311.44

these values in BNB or USDT?

**Comment by fabiensabatie** [comment]
Hi there @frodoe7 

I haven't given this project any attention for a couple years now, happy to see you use it ! 

Yes, these values are in USD !

**Comment by frodoe7** [comment]
@fabiensabatie 
I could not find any good backtesting library in NodeJS eco-system
so, thanks for your contribution,

what if I trade in ETHBTC for example, you always convert to USD?
also, do you have any contact method? may have extra couple of questions

**Comment by fabiensabatie** [comment]
That's a good point, I wasn't sure so i had to check my code 

From https://github.com/fabiensabatie/yieldfinity/blob/main/src/domain/entities/orders/order.ts, the profit is just the difference between the candle closing value and the starting price, so it's not in USD, my bad.

For each pair X/Y, the price is given in Y !

Sure thing, contact me via email at fabien.sabatie@live.fr, i'll send you my number so we can chat !

**Comment by frodoe7** [comment]
Thanks too much, will contact you Fabien
